# Generated by Django 5.1.1 on 2024-09-21 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agenda_pacientes', '0002_rename_nome_paciente_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paciente',
            old_name='text',
            new_name='nome',
        ),
    ]
