# Generated by Django 5.1.1 on 2024-09-26 23:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda_pacientes', '0006_alter_consulta_paciente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agenda_pacientes.paciente'),
        ),
    ]
